	keycode_invalid	=$ff
	
	keycode_del	=$00
	keycode_3	=$01
	keycode_5	=$02
	keycode_7	=$03
	keycode_9	=$04
	keycode_plus	=$05
	keycode_pound	=$06
	keycode_1	=$07
			
	keycode_return	=$10
	keycode_w	=$11
	keycode_r	=$12
	keycode_y	=$13
	keycode_i	=$14
	keycode_p	=$15
	keycode_star	=$16
	keycode_leftarrow	=$17

	keycode_crsr_rl	=$20
	keycode_a	=$21
	keycode_d	=$22
	keycode_g	=$23
	keycode_j	=$24
	keycode_l	=$25
	keycode_semicolon	=$26
	keycode_ctrl	=$27

	keycode_f7	=$30
	keycode_4	=$31
	keycode_6	=$32
	keycode_8	=$33
	keycode_0	=$34
	keycode_minus	=$35
	keycode_home	=$36
	keycode_2	=$37

	keycode_f1	=$40
	keycode_z	=$41
	keycode_c	=$42
	keycode_b	=$43
	keycode_m	=$44
	keycode_dot	=$45
	keycode_shift_r	=$46
	keycode_space	=$47

	keycode_f3	=$50
	keycode_s	=$51
	keycode_f	=$52
	keycode_h	=$53
	keycode_k	=$54
	keycode_colon	=$55
	keycode_equal	=$56
	keycode_cbm	=$57

	keycode_f5	=$60
	keycode_e	=$61
	keycode_t	=$62
	keycode_u	=$63
	keycode_o	=$64
	keycode_at	=$65
	keycode_uparrow	=$66
	keycode_q	=$67

	keycode_crsr_ud	=$70
	keycode_shift_l	=$71
	keycode_x	=$72
	keycode_v	=$73
	keycode_n	=$74
	keycode_comma	=$75
	keycode_slash	=$76
	keycode_stop	=$77
