

all: spritecrunch.prg spritecrunch2.prg

spritecrunch.prg: spritecrunch.asm
	KickAss spritecrunch.asm
spritecrunch2.prg: spritecrunch2.asm
	KickAss spritecrunch2.asm

clean:
	rm -f *~ *.sym
	rm -f spritecrunch.prg
	rm -f spritecrunch2.prg
