
all:
	make -C util
	make -C selftest
	make -C pwm
	make -C scanner
	make -C interrupts
	make -C viavarious

clean:
	make -C util clean
	make -C selftest clean
	make -C pwm clean
	make -C scanner clean
	make -C interrupts clean
	make -C viavarious clean
	rm -f *~
